sudo: false
language: cpp
env:
  matrix:
  - PRK_TARGET=allserial
  - PRK_TARGET=allfortranserial
  - PRK_TARGET=allfortranopenmp
  - PRK_TARGET=allfortranpretty
  - PRK_TARGET=allfortrancoarray
  - PRK_TARGET=allopenmp
  - PRK_TARGET=allmpi1
  - PRK_TARGET=allshmem
  global:
    secure: Dzsj5Tedmm3AswWKQ+nSbXXzPZjlIF7vNRCsAIESAFvMu4re0Boj5+YnWox54SEQ63P+lOZakJYu2TFLMsLyadxDL9T+Vy/p8smZpGnf5KrqMhjW5+SFokUAwSUCAteTaUdH+DiofFpbfaUD9sUK0phxAvx/mMwqe4JTxAjrEepz7tbmWZw82FTh2SfWYpX0ikewyPm7XY1kgaeEvK5vCjBiW10kcpd/V+fDeDB2W6YcT328OhjL2hIOb5t50Ss24PVZ+NpMNneyMdZdDhFCC+e3rPAyfu3FVIp7AIBIqee8Br0+LTMe36CBj/tOLWblK4GzPjPdaf1JibMwjiBQ9gJN8o05ge05I0H3Yj1OtFRZ4eideXVBjX9VUyJSM1YMgP4z51MZ+tHUhjyN93HONUExHUQPHcOyQCdKCoTKN1qr4vPHEaMt/Fy8oateQQH13Tiqz2y++7qhluVHgbiU/kOVhBOTiryW68UKh6OfAEAcLYpT0MbfEgjUbLIVQxRNY1ZrSGmJNW3294URcFUjbaLpgp60j3qnKz5eEISBwaBvibgO4CMOKDCRoJBHdMQ/liE5Bp96itB5scBd++fR2tfoEoLAOROeKHcY3A+uVfi0AxcDuLj9RZ5bBR0F4H5K3dyB2rI+p6UZxGiWxsEPVybgfEEzma2OGi/wCQXOKj8=
virtualenv:
  system_site_packages: true
os:
- linux
compiler:
- clang
- touch ~/use-intel-compilers ; gcc
matrix:
  exclude:
  - os: osx
    compiler: touch ~/use-intel-compilers ; gcc
  - os: linux
    compiler: clang
    env: PRK_TARGET=allopenmp
  - os: linux
    compiler: clang
    env: PRK_TARGET=allmpiomp
  - os: osx
    compiler: gcc
    env: PRK_TARGET=allopenmp
  - os: osx
    compiler: gcc
    env: PRK_TARGET=allmpiomp
  - compiler: clang
    env: PRK_TARGET=allupc UPC_IMPL=gupc
  - compiler: touch ~/use-intel-compilers ; gcc
    env: PRK_TARGET=allupc UPC_IMPL=gupc
  - os: osx
    env: PRK_TARGET=allupc UPC_IMPL=gupc
  - compiler: clang
    env: PRK_TARGET=allupc UPC_IMPL=gupc
  - os: osx
    env: PRK_TARGET=allfgmpi
  - compiler: gcc
    env: PRK_TARGET=allgrappa
  - os: osx
    env: PRK_TARGET=allchapel CHPL_COMM=gasnet
  - env: PRK_TARGET=allupc UPC_IMPL=bupc GASNET_CONDUIT=ofi PRK_FLAGS="-Wc,-O3"
  - os: linux
    compiler: gcc
    env: PRK_TARGET=allhpx5
  - os: linux
    env: PRK_TARGET=allhpx3
  - compiler: clang
    env: PRK_TARGET=allfortranserial
  - compiler: clang
    env: PRK_TARGET=allfortranopenmp
  - compiler: clang
    env: PRK_TARGET=allfortranpretty
  - compiler: clang
    env: PRK_TARGET=allfortrancoarray
  - compiler: gcc
    env: PRK_TARGET=allpython
  - compiler: gcc
    env: PRK_TARGET=alljulia
  allow_failures:
  - env: PRK_TARGET=allpython
  - os: linux
    env: PRK_TARGET=alljulia
  - os: linux
    compiler: gcc
    env: PRK_TARGET=allfortrancoarray
  - os: osx
    env: PRK_TARGET=allupc UPC_IMPL=bupc GASNET_CONDUIT=mpi PRK_FLAGS="-Wc,-O3"
  - os: osx
    env: PRK_TARGET=allupc UPC_IMPL=bupc GASNET_CONDUIT=udp PRK_FLAGS="-Wc,-O3"
  - os: osx
    env: PRK_TARGET=allupc UPC_IMPL=bupc GASNET_CONDUIT=smp PRK_FLAGS="-Wc,-O3"
  - env: PRK_TARGET=allupc UPC_IMPL=gupc
  - env: PRK_TARGET=allgrappa
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allfgmpi
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allampi
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allcharm++
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allupc
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allhpx3
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allhpx5
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=allchapel
  - compiler: touch /use-intel-compilers ; gcc
    env: PRK_TARGET=alllegion
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python-numpy
    - libnuma-dev
    - cmake
    - gcc-4.8
    - g++-4.8
    - gfortran-4.8
    - gcc-4.9
    - g++-4.9
    - gfortran-4.9
    - gcc-5
    - g++-5
    - gfortran-5
before_install:
- pwd
- export TRAVIS_HOME=$PWD
- export TRAVIS_ROOT=$TRAVIS_HOME/PRK-deps
- mkdir -p $TRAVIS_ROOT
- sh ./travis/install-intel.sh $TRAVIS_ROOT $PRK_TARGET
- source ~/.bashrc
install:
- export PATH=$TRAVIS_ROOT/bin:$PATH
- export PATH=$TRAVIS_ROOT/gcc/bin:$PATH
- export PATH=$TRAVIS_ROOT/cmake/bin:$PATH
- sh ./travis/install-deps.sh $TRAVIS_ROOT $PRK_TARGET
before_script:
- pwd
script:
- sh ./travis/build-run-prk.sh $TRAVIS_ROOT $PRK_TARGET
after_failure:
- echo "Sad panda"
notifications:
  email:
    recipients:
    - jeff.science@gmail.com
    on_success:
    - change
    on_failure:
    - always
