# required for package manager installs
#sudo: true
language: c
os:
  - linux
# OpenMP compiler support on Mac is an issue
#  - osx
compiler:
  - gcc
#  - clang
env:
  - PRK_TARGET=allserial
  - PRK_TARGET=allopenmp
#  - PRK_TARGET=allmpi1
#  - PRK_TARGET=allfgmpi
#  - PRK_TARGET=allmpiopenmp
#  - PRK_TARGET=allmpishm
#  - PRK_TARGET=allmpirma
#  - PRK_TARGET=allshmem
#  - PRK_TARGET=allupc
#  - PRK_TARGET=allcharm++
#  - PRK_TARGET=allampi
#  - PRK_TARGET=allgrappa
before_install:
  - sh ./travis/install-deps.sh $PRK_TARGET
script:
  - sed -e "s/MYCC/gcc/"               < common/make.defs.in > common/make.defs.1
  - sed -e "s/MYCXX/g++/"              < common/make.defs.1  > common/make.defs.2
  - sed -e "s/MYOPENMPFLAG/-fopenmp/"  < common/make.defs.2  > common/make.defs
  - echo -e "SHMEMCC=oshcc\nSHMEMTOP=$$TRAVIS_INSTALL\n" > common/make.defs
  - cat common/make.defs
  - sh ./travis/build-run-prk.sh $PRK_TARGET
after_failure:
  - echo "Sad panda"
notifications:
  email:
    #recipients:
    #  - rob.f.van.der.wijngaart@intel.com
    #  - jeff.r.hammond@intel.com
    on_success: [change]
    on_failure: [always]
