language: c
os:
  - linux
#  - osx
compiler:
  - gcc
#  - clang
env:
  - PRK_TARGET=allserial
#  - PRK_TARGET=allopenmp
#  - PRK_TARGET=allmpi1
#  - PRK_TARGET=allfgmpi
#  - PRK_TARGET=allmpiopenmp
#  - PRK_TARGET=allmpishm
#  - PRK_TARGET=allmpirma
#  - PRK_TARGET=allshmem
#  - PRK_TARGET=allupc
#  - PRK_TARGET=allcharm++
#  - PRK_TARGET=allampi
#  - PRK_TARGET=allgrappa
before_install:
  - echo $(CC)
  - echo $(CXX)
  - sed -e "s/MYCC/$(CC)/g"              < common/make.defs.in > common/make.defs.1
  - sed -e "s/MYCXX/$(CXX)/g"            < common/make.defs.1  > common/make.defs
  - cat common/make.defs
  - sh ./travis/install-deps.sh $PRK_TARGET
script:
  - sh ./travis/build-run-prk.sh $PRK_TARGET
after_failure:
  - cat ./config.log
  - head -n100 ./test/*.log
notifications:
  email:
    recipients:
      - rob.f.van.der.wijngaart@intel.com
      - jeff.r.hammond@intel.com
    on_success: [change]
    on_failure: [always]
